app/administration/__init__.py
from flask import Blueprint

bp = Blueprint('administration', __name__)

from app.administration import routes

app/administration/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from app import db
from app.models import User, Role
from app.administration import bp
import sys


@bp.route('/create_user', methods=['GET', 'POST'])
@login_required
def create_user():
    if current_user.role.name == 'admin':
        if request.method == 'GET':
            roles = Role.query.all()
            return render_template('administration/create_user.html', roles=roles)
        elif request.method == 'POST':
            role_id = request.form.get('roleId')
            username = request.form.get('username')
            email = request.form.get('email')
            users = User.query.all()
            if username in (user.username for user in users):
                return "ALREADY EXISTS"
            password = request.form.get('password')
            role = Role.query.filter_by(id=role_id).first()

            user = User(username=username, email=email,
                        role=role, auto_save_code=True)
            user.set_password(password)
            db.session.add(user)
            db.session.commit()
            users = User.query.all()
            return render_template('administration/users.html', users=users)


@bp.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    if current_user.role.name == 'admin':
        users = User.query.all()
    return render_template('administration/users.html', users=users)

app/templates/administration/create_user.html
{% extends 'base.html' %} {% block app_content %}
<h1>Create user</h1>
<form
    action="{{ url_for('administration.create_user') }}"
    method="POST"
    id="createUserForm"
    class="form-signin"
    autocomplete="off"
>
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" name="username" id="username" autocomplete="off" />
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" name="password" id="password" autocomplete="off" />
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" name="email" id="email" autocomplete="off" />
    </div>
    <div class="form-group">
        <label for="role">Role:</label>
        <select class="form-control" name="roleId">
            {% for role in roles %} {% if role.name == 'student' %}
            <option value="{{ role.id }}" selected>{{ role.name }}</option>
            {% else %}
            <option value="{{ role.id }}">{{ role.name }}</option>
            {% endif %} {% endfor %}
        </select>
    </div>
    <input type="submit" id="submit" class="btn btn-lg btn-primary btn-block" value="Add user" />
</form>
{% endblock %}

app/templates/administration/users.html
{% extends 'base.html' %} {% block app_content %}
<h1>Users</h1>
<div class="row">
    <div class="col-md-2">
        <a href="{{ url_for('administration.create_user') }}" class="btn btn-primary width100">Add user</a>
    </div>
</div>
<br />
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Role</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>
                    {{ user.username }}
                </td>
                <td>
                    {{ user.role.name }}
                </td>
            </tr>
            {% else %}
            <tr>
                <td colspan="2">No users</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}