app/assignments/__init__.py
from flask import Blueprint

bp = Blueprint('assignments', __name__)

from app.assignments import routes

app/assignments/routes.py
# coding=utf-8
import io
import os
import json
import sys
from flask import make_response, render_template, flash, redirect, url_for, request, \
    current_app
from flask_login import login_required, current_user
from app import db
from app.models import Course, Assignment, Solution, Test, Code, Template, User
from app.assignments import bp
from werkzeug.utils import secure_filename
from flask import jsonify
import datetime
import uuid
import time
import re
from shutil import copyfile
import platform
from datetime import datetime, timedelta

_GRADE = {'PASS': 1, 'FAIL': 2, 'PARTIAL': 3}

@bp.route("/assignment/<int:id>", methods=["GET", "POST"])
@login_required
def assignment(id):
    assignment = Assignment.query.filter_by(id=id).first_or_404()
    return render_template("assignments/assignment.html",
                           assignment=assignment)


@bp.route("/assignment/description/<int:assignment_id>", methods=["GET", "POST"])
@login_required
def description(assignment_id):
    assignment = Assignment.query.filter_by(id=assignment_id).first_or_404()
    description = assignment.description if assignment.description else ''
    sample_input = assignment.sample_input if assignment.sample_input else ''
    sample_output = assignment.sample_output if assignment.sample_output else ''
    test_data = assignment.test_data if assignment.test_data else ''
    time_limit = assignment.time_limit if assignment.time_limit else ''

    full_description = description + \
        "\n #### Input\n" + sample_input + \
        "\n #### Output\n" + sample_output + \
        "\n #### Time limit\n" + str(time_limit) + "s"

    response = {"description": full_description, "test_data": test_data}
    return jsonify(response)


@bp.route("/course/<int:course_id>/add_assignment", methods=["GET", "POST"])
@login_required
def add_assignment(course_id):
    course = Course.query.filter_by(id=course_id).first_or_404()
    if request.method == 'POST':
        existing_assignment = Assignment.query.filter_by(
            title=request.form["title"]).first()
        if existing_assignment is not None:
            flash("Use different title")
            return redirect(url_for('assignments.add_assignment', course_id=course.id))

        assignment = Assignment()
        assignment.title = request.form['title']
        assignment.course = course
        assignment.description = request.form['description']
        assignment.sample_input = request.form['sample_input']
        assignment.sample_output = request.form['sample_output']
        assignment.test_data = request.form['test_data']
        if request.form['time_limit'] != '' and is_number(request.form['time_limit']):
            assignment.time_limit = request.form['time_limit']

        db.session.add(assignment)
        db.session.commit()
        flash("Successfully added new assignment to {}".format(course.title))
        return redirect(url_for("assignments.assignment", id=assignment.id))

    return render_template("assignments/add_assignment.html", title="Add assignment", course=course)


@bp.route("/assignment/<int:id>/edit", methods=["GET", "POST"])
@login_required
def edit_assignment(id):
    assignment = Assignment.query.filter_by(id=id).first()
    if request.method == 'POST':
        assignment.title = request.form['title']
        assignment.description = request.form['description']
        assignment.sample_input = request.form['sample_input']
        assignment.sample_output = request.form['sample_output']
        assignment.test_data = request.form['test_data']
        if request.form['time_limit'] != '' and is_number(request.form['time_limit']):
            assignment.time_limit = request.form['time_limit']

        db.session.commit()
        flash("Successfully saved changes")
        return redirect(url_for("assignments.assignment", id=id))

    return render_template("assignments/edit_assignment.html",
                           title="Edit assignment",
                           assignment=assignment)


@bp.route("/editor/<int:assignment_id>", methods=["GET"])
@login_required
def editor(assignment_id):
    tab = request.args.get("tab")
    code = ""
    solution = None

    assignment = Assignment.query.filter_by(id=assignment_id).first()

    template = assignment.template
    template_code = read_file(template.code.path) if template else ""

    if current_user.role.name in ["teacher", "admin"]:
        if tab == "solution":
            solution = Solution.query.filter_by(
                assignment_id=assignment.id, is_default=True).first()
            if solution:
                solution_code = read_file(
                    solution.code.path) if solution else ""
                code = solution_code
            if code == "":
                code = template_code
        elif tab == "test":
            test = assignment.test
            test_code = read_file(test.code.path) if test else ""
            code = test_code
        else:
            code = template_code
    else:
        solution = Solution.query.filter_by(
            assignment_id=assignment.id, is_default=False, is_submitted=False, user_id=current_user.id).first()
        if solution:
            solution_code = read_file(solution.code.path) if solution else ""
            code = solution_code
        if code == "":
            code = template_code

    return render_template("editor.html", assignment=assignment, code=code, solution=solution)


@bp.route("/upload_file", methods=["POST", "GET"])
@login_required
def upload_file():
    resp = {}
    if request.method == "POST":
        tab = request.form.get("tab")
        assignment_id = request.form.get("assignment_id")

        if "file" not in request.files:
            resp = {"message": "No file part", "status": 1}
            return jsonify(resp)

        file = request.files["file"]

        if file.filename == "":
            resp = {"message": "No selected file", "status": 1}
            return jsonify(resp)

        if file and allowed_file(file.filename):
            code = file.read().decode("utf-8")
            save_code_to_file(assignment_id, tab, code)
        resp = {"message": "Succesfully uploaded file", "status": 1}
    else:
        resp = {"message": "No selected file", "status": 1}

    return jsonify(resp)


def save_solution(assignment, path):
    code = Code()
    solution = Solution()

    if current_user.role.name in ["teacher", "admin"]:
        solution = Solution.query.filter_by(
            assignment_id=assignment.id, is_default=True).first()
        if not solution:
            solution = Solution()
            solution.is_default = True
    else:
        solution = Solution.query.filter_by(
            assignment_id=assignment.id, is_default=False, is_submitted=False, user_id=current_user.id).first()
        if not solution:
            solution = Solution()
            solution.is_default = False

    solution.set_user(current_user)
    solution.set_assignment(assignment)

    # no multiple solutions only one code..
    if solution and solution.code:
        code = solution.code

    code.path = path
    solution.set_code(code)

    db.session.add(assignment)
    db.session.add(code)
    db.session.add(solution)
    db.session.commit()


def save_test(assignment, path):
    code = Code()

    if assignment.test:
        test = assignment.test
        if test.code:
            code = test.code
        else:
            code.path = path
    else:
        test = Test()
        assignment.set_test(test)
        code.path = path

    test.set_code(code)
    db.session.add(code)
    db.session.add(test)
    db.session.add(assignment)
    db.session.commit()


def save_template(assignment, path):
    code = Code()

    if assignment.template:
        template = assignment.template
        if template.code:
            code = template.code
        else:
            code.path = path
    else:
        template = Template()
        assignment.set_template(template)
        code.path = path

    template.set_code(code)
    db.session.add(code)
    db.session.add(template)
    db.session.add(assignment)
    db.session.commit()


@bp.route("/save_code/<int:assignment_id>", methods=["POST"])
@login_required
def save_code(assignment_id):
    if request.method == "POST":
        code = request.form.get("code")
        tab = request.form.get("tab")
        save_code_to_file(assignment_id, tab, code)
    return "OK"


@bp.route("/run_code/<int:assignment_id>", methods=["POST"])
@login_required
def run_code(assignment_id):
    assignment = Assignment.query.filter_by(id=assignment_id).first()

    test_data = parse_test_data(assignment.test_data, 3)
    results = []

    for i in range(0, len(test_data["test_inputs"])):
        test = test_data["test_inputs"][i]
        output = test_data["test_outputs"][i]

        result = run_just_code(assignment, test)
        result_text = ""
        output = output.replace('\r', '').replace('\n', '').replace(' ', '')
        result_output = result["result"].replace(
            '\r', '').replace('\n', '').replace(' ', '')

        result_text = "TEST {}\nINPUT: {} \nOUTPUT: {} \nTIME: {}s".format(i +1, test, result_output, result["time"])
        results.append({'message': result_text})
        
    return jsonify(results)


def save_code_to_file(assignment_id, tab, code):
    assignment = Assignment.query.filter_by(id=assignment_id).first()
    filename = ""

    if tab == "solution":
        filename = get_filename_for_existing_solution(assignment)
    elif tab == "test":
        filename = get_filename_for_existing_test(assignment)
    elif tab == "template":
        filename = get_filename_for_existing_template(assignment)

    if filename != "":
        path = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)
    else:
        filename = secure_filename("{}.py".format(str(uuid.uuid4())))
        file_path = current_app.config["UPLOAD_FOLDER"]

app/templates/assignments/add_assignment.html
{% extends "base.html" %} {% block app_content %}
<h1>Add assignment</h1>
<form action="{{url_for('assignments.add_assignment', course_id=course.id)}}" method="POST">
    <div class="form-group">
        <label for="titleInput">Title</label>
        <input id="titleInput" type="text" name="title"  placeholder='Assignment title' required class="form-control">
    </div>
    <div class="form-group">
        <label for="descriptionTextarea">Description</label>
        <textarea id="descriptionTextarea" class="form-control"  placeholder='Assignment description' required name="description"></textarea>
    </div>
        <div class="form-group">
            <label for="sampleInput">Input</label>
            <textarea id="sampleInput"  placeholder='Describe input data' class="form-control"
                name="sample_input"></textarea>
        </div>
        <div class="form-group">
            <label for="sampleOutput">Output</label>
            <textarea id="sampleOutput"  placeholder='Describe output data' class="form-control"
                name="sample_output"></textarea>
        </div>
        <div class="form-group">
            <label for="timeLimit">Time limit</label>
            <input id="timeLimit" class="form-control" name="time_limit" type="number" placeholder='Time limit in seconds'></input>
        </div>
        <div class="form-group">
            <label for="testData">Test data</label>
            <textarea id="testData" class="form-control"  placeholder='Input and output divided by comma, only array and integer supported.' name="test_data"></textarea>
        </div>
    <button class="btn btn-md btn-primary" type="submit">Save</button>
</form>
{% endblock %}

app/templates/assignments/assignment.html
{% extends 'base.html' %} {% block app_content %}
<h1>{{ assignment.title }}</h1>
<div id="markdownDesc"></div>
<br />
<div class="row">
    <div class="col-md-2">
        {% if current_user.role.name in ['teacher', 'admin'] %}
        <a href="{{url_for('assignments.edit_assignment', id=assignment.id)}}" class="btn btn-primary width100">Edit</a>
        {% endif%}
    </div>
    {% if current_user.role.name == 'admin' %}
    <div class="col-md-2">
        <a href="{{url_for('assignments.export', id=assignment.id)}}" class="btn btn-primary width100">Export</a>
    </div>
    {% endif%}
</div>
<div id="editorHolder"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/9.1.0/markdown-it.min.js"></script>
<script>
    function loadMarkdownDescription(){
        $.ajax({
            url: '{{ url_for('assignments.description', assignment_id=assignment.id) }}',
            success: function (response) {
                var converter = window.markdownit();
                var html = converter.render(response.description);
                html  = html + '<h4>Test data</h4><table><tr><td><b>Inputs</b></td>';
                var testData = extractTestData(response.test_data);
                for(var input of testData.inputs){
                    html = html + '<td>'+ input + '</td>';
                }

                html = html + '</tr><tr><td><b>Outputs</b></td>';

                for(var output of testData.outputs){
                    html = html + '<td>'+ output + '</td>';
                }
                html = html + '</tr></table>';
                $("#markdownDesc").html(html);
            },
            error: function () {
            }
        });

    }

    function loadEditor(tab) {
        var editorHolder = $("#editorHolder");

        $.ajax({
            data: { tab: tab },
            url: '{{ url_for('assignments.editor', assignment_id=assignment.id) }}',
            success: function (response) {
                editorHolder.empty();
                editorHolder.html(response);
                init(tab);
            },
            error: function () {

            }
        });
    }

    function extractTestData(testData){
        var rows = testData.split('\n');
        var inputs = [];
        var outputs = [];

        var n = rows.length >= 3 ? 3: rows.length

        for(var i = 0; i < n; i++){
            var row = rows[i];
            row.trim();
            var inputRx = /\[(.*?)\]/;
            var input = row.match(inputRx);
            var output = '';

            if (input){
                outputCandidate = row.replace(input[0] + ',', '');
                output = outputCandidate.match(inputRx);
                if(output){
                    output = output[0];
                }else{
                    output = outputCandidate
                }

                input = input[0];
            }else{
                var rowArray = row.split(',');
                input = rowArray[0];
                output = rowArray[1];
            }

            inputs.push(input);
            outputs.push(output);

        }
        return {inputs: inputs,  outputs: outputs};
    }

    window.onload = function () {
        loadEditor('solution');
        loadMarkdownDescription();
    };
</script>
{% endblock %}

app/templates/assignments/edit_assignment.html
{% extends "base.html" %} {% block app_content %}
<h1>Edit assignment</h1>
<form action="{{url_for('assignments.edit_assignment', id=assignment.id)}}" method="POST">
    <div class="form-group">
        <label for="titleInput">Title</label>
        <input placeholder='Assignment title' id="titleInput" type="text" name="title" class="form-control" value="{{ assignment.title }}" />
    </div>
    <div class="form-group">
        <label for="descriptionTextarea">Description</label>
        <textarea placeholder='Assignment description' id="descriptionTextarea" class="form-control" name="description">{{
            assignment.description
        }}</textarea>
    </div>
    <div class="form-group">
        <label for="sampleInput">Input</label>
        <textarea placeholder='Describe input data'
            id="sampleInput"
            class="form-control"
            name="sample_input"
            >{{ assignment.sample_input if assignment.sample_input else '' }}</textarea
        >
    </div>
    <div class="form-group">
        <label for="sampleOutput">Output</label>
        <textarea placeholder='Describe output data'
            id="sampleOutput"
            class="form-control"
            name="sample_output"
            >{{ assignment.sample_output if assignment.sample_output else '' }}</textarea
        >
    </div>
    <div class="form-group">
        <label for="timeLimit">Time limit</label>
        <input placeholder='Time limit in seconds'
            id="timeLimit"
            class="form-control"
            name="time_limit"
            type="number"
            value="{{ assignment.time_limit if assignment.time_limit else '' }}"
            ></input>
    </div>
    <div class="form-group">
        <label for="testData">Test data</label>
        <textarea placeholder='Input and output divided by comma, only array and integer supported.' id="testData" class="form-control" name="test_data">{{ assignment.test_data if assignment.test_data else '' }}</textarea>
    </div>
    <button class="btn btn-md btn-primary" type="submit">Save</button>
</form>
{% endblock %}