app/courses/__init__.py
from flask import Blueprint

bp = Blueprint('courses', __name__)

from app.courses import routes

app/courses/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from app import db
from app.models import Course, Assignment, User, Solution
from app.courses import bp


@bp.route('/courses', methods=['GET', 'POST'])
@login_required
def courses():
    if(current_user.role.name in ['teacher', 'student']):
        courses = current_user.courses
    else:
        courses = Course.query.all()
    return render_template('courses/courses.html', courses=courses, title="Courses")


@bp.route('/course/<int:id>', methods=['GET'])
@login_required
def course(id):
    course = Course.query.filter_by(id=id).first()
    assignments = Assignment.query.filter_by(course=course)
    if current_user.role.name not in ['teacher', 'admin']:
        completed_assignments = []

        for assignment in assignments:
            default_solution = Solution.query.filter_by(
                assignment_id=assignment.id, is_default=True).first()

            if default_solution and assignment.test and assignment.template:
                completed_assignments.append(assignment)

        assignments = completed_assignments

    return render_template('courses/course.html', assignments=assignments, course=course)


@bp.route('/add_course', methods=['GET', 'POST'])
@login_required
def add_course():
    if request.method == 'POST':
        course = Course(title=request.form['title'])
        db.session.add(course)
        db.session.commit()

        current_user.enroll(course)
        db.session.commit()
        flash('Successfully added new course.')
        return redirect(url_for('courses.course', id=course.id))

    return render_template('courses/add_course.html', title='Add course',)


@bp.route('/course/<int:id>/edit', methods=['GET', 'POST', 'PUT'])
@login_required
def edit_course(id):
    course = Course.query.filter_by(id=id).first()

    if request.method == 'POST':
        course.title = request.form['title']
        db.session.commit()
        flash('Successfully saved changes.')
        return redirect(url_for('courses.course', id=id))

    return render_template('courses/edit_course.html', title='Edit course', course=course)


@bp.route('/course/<int:id>/users', methods=['GET', 'POST'])
@login_required
def users(id):
    course = Course.query.filter_by(id=id).first()
    users = course.users

    if(current_user.role.name == 'teacher' and current_user in users) or current_user.role.name == 'admin':
        return render_template('courses/users.html', title='Course users',
                               users=users, course=course)


@bp.route('/course/<int:id>/enrolling', methods=['GET', 'POST'])
@login_required
def enrolling(id):
    course = Course.query.filter_by(id=id).first()
    enrolled_users = course.users
    all_users = db.session.query(User).all()  # TODO dont put admin here

    not_enrolled_users = [
        user for user in all_users if user not in enrolled_users]

    if(current_user.role.name == 'teacher' and current_user in enrolled_users) or current_user.role.name == 'admin':
        return render_template('courses/enrolling.html', title='Enroll users',
                               users=not_enrolled_users, course=course)
    # Handle unauthorized


@bp.route('/course/<int:id>/enroll/<int:user_id>', methods=['GET', 'POST'])
def enroll(id, user_id):
    course = Course.query.filter_by(id=id).first()
    user = User.query.filter_by(id=user_id).first()
    user.enroll(course)
    db.session.commit()
    flash("Succesfully enrolled {} into {}".format(user.username, course.title))

    return redirect(url_for('courses.users', id=id))


@bp.route('/course/<int:id>/ban/<int:user_id>', methods=['GET', 'POST'])
def ban(id, user_id):
    # you can't ban yourself
    course = Course.query.filter_by(id=id).first()
    user = User.query.filter_by(id=user_id).first()
    if(user != current_user):
        user.withdraw(course)
        db.session.commit()
        flash("Succesfully banned {} from {}".format(
            user.username, course.title))
    else:
        flash("You can't ban yourself.")
    return redirect(url_for('courses.users', id=id))

app/templates/courses/add_course.html
{% extends "base.html" %} {% block app_content %}
<h1>Add course</h1>
<form action="{{url_for('courses.add_course')}}" method="POST">
    <div class="form-group">
        <label for="title"></label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Enter title">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

app/templates/courses/course.html
{% extends 'base.html' %} {% block app_content %}
<h1>
    <b>{{ course.title }}</b> assignments
</h1>
<div class="row">
    {% if current_user.role.name in ['teacher', 'admin'] %}
    <div class="col-md-2">
        <a href="{{url_for('assignments.add_assignment', course_id=course.id)}}" class="btn btn-primary width100"
            >Add assignment</a
        >
    </div>
    <div class="col-md-2">
        <a href="{{url_for('courses.edit_course', id=course.id)}}" class="btn btn-primary width100">Edit</a>
    </div>
    <div class="col-md-2">
        <a href="{{url_for('courses.users', id=course.id)}}" class="btn btn-primary width100">Users</a>
    </div>
    {% endif %}
</div>
<br />
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            {% for assignment in assignments %}
            <tr>
                <td>
                    <a href="{{url_for('assignments.assignment', id=assignment.id)}}">{{ assignment.title }}</a>
                </td>
            </tr>
            {% else %}
            <tr>
                <td>No assignments</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/courses/courses.html
{% extends 'base.html' %} {% block app_content %}
<h1>{{title}}</h1>
{% if current_user.role.name in ['teacher', 'admin'] %}
<div class="row">
    <div class="col-md-12">
        <a href="{{url_for('courses.add_course')}}" class="btn btn-primary">Add new</a>
    </div>
</div>
<br>
{% endif %}

<div class="table-responsive"> 
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
                {% for course in courses %}
                <tr>
                    <td> <a href="{{url_for('courses.course', id=course.id)}}">{{ course.title }}</a></td>
                </tr>
                {% else %}
                <tr>
                    <td> No courses</td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/courses/edit_course.html
{% extends "base.html" %} {% block app_content %}
<h1>Edit course</h1>
<form action="{{url_for('courses.edit_course', id=course.id)}}" method="POST">
    <div class="form-group">
        <label for="title"></label>
        <input type="text" class="form-control" id="title" name="title" value="{{course.title}}"
            placeholder="Enter title">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

app/templates/courses/enrolling.html
{% extends 'base.html' %} {% block app_content %}
<h1>Enroll users in <b>{{course.title}}</b></h1>
<div class="table-responsive"> 
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>User</th>
                <th>Email</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
                {% for user in users %}
                <tr>
                    <td> {{ user.username }}</td>
                    <td> {{ user.email }}</td>
                    <td> {{ user.role.name }}</td>
                    <td><a href="{{url_for('courses.enroll', id=course.id, user_id=user.id)}}">Enroll</a></td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
</div>
 {% endblock %}

app/templates/courses/users.html
{% extends 'base.html' %} {% block app_content %}
<h1>Users enrolled in <b>{{course.title}}</b></h1>
<div class="row">
    <div class="col-md-10">
        <a href="{{url_for('courses.enrolling', id=course.id)}}" class="btn btn-primary">Enroll user</a>
    </div>
</div>
<div class="table-responsive"> 
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>User</th>
                <th>Email</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
                {% for user in users %}
                <tr>
                    <td> {{ user.username }}</td>
                    <td> {{ user.email }}</td>
                    <td> {{ user.role.name }}</td>
                    <td><a href="{{url_for('courses.ban', id=course.id, user_id=user.id)}}">Ban</a></td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
</div>
 {% endblock %}